assign_issues:
  - GoogleCloudPlatform/java-samples-reviewers

assign_issues_by:
- labels:
  - 'api: logging'
  - 'api: clouderrorreporting'
  to:
  - simonz130
- labels:
  - 'api: cloudiot'
  to:
  - attilagargyan
  - simoncsaba-g
- labels:
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  to:
  - GoogleCloudPlatform/cloud-native-db-dpes
- labels:
  - 'api: cloudsql'
  to:
  - GoogleCloudPlatform/infra-db-dpes
- labels:
  - 'api: spanner'
  to:
  - rajatbhatta
- labels:
  - 'api: dlp'
  to:
  - GoogleCloudPlatform/googleapis-dlp
- labels:
  - 'api: datacatalog'
  - 'api: dataplex'
  to:
  - GoogleCloudPlatform/googleapi-dataplex
  
assign_prs:
  - GoogleCloudPlatform/java-samples-reviewers

assign_prs_by:
- labels:
  - 'api: logging'
  - 'api: clouderrorreporting'
  to:
  - simonz130
- labels:
  - 'api: cloudiot'
  to:
  - attilagargyan
  - simoncsaba-g
- labels:
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  to:
  - GoogleCloudPlatform/cloud-native-db-dpes
- labels:
  - 'api: cloudsql'
  to:
  - GoogleCloudPlatform/infra-db-dpes
- labels:
  - 'api: dlp'
  to:
  - GoogleCloudPlatform/googleapis-dlp
- labels:
  - 'api: datacatalog'
  - 'api: dataplex'
  to:
  - GoogleCloudPlatform/googleapi-dataplex
